[project]
name = "Lobster-ECOL"
version = "0.1.0"
description = "Add a short description here"
authors = ["adamkemberling <adamkemberling@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
xarray = ">=2025.4.0,<2025.5"
geopandas = ">=1.1.0,<1.2"
matplotlib = ">=3.10.3,<3.11"
shapely = ">=2.1.1,<2.2"
ipykernel = ">=6.29.5,<6.30"
pip = ">=25.1.1,<25.2"
dask = ">=2025.5.1,<2025.6"
xesmf = ">=0.6.0,<0.7"
scipy = ">=1.15.2,<1.16"
pyproj = ">=3.7.1,<3.8"
rioxarray = ">=0.19.0,<0.20"
tqdm = ">=4.67.1,<4.68"
esmf = ">=8.8.1,<8.9"
pydap = ">=3.5.5,<3.6"
netcdf4 = ">=1.7.2,<1.8"
regionmask = ">=0.13.0,<0.14"
